### ISSUE TITLE
UAC on startup

### ISSUE THREAD

**Issue by dsferruzza** [alphaonex86/Supercopier#2]
Hi!

I saw in the todo list (https://github.com/alphaonex86/Supercopier/blob/master/todo.txt#L6) that you have a problem with UAC on Supercopier's startup.
This is, for me, the only thing that prevent to test it in a daily basis.

I know [CCleaner](https://www.piriform.com/ccleaner) uses a method involving the Task Scheduler to avoid the UAC prompt to appear.
I found this article : http://www.msfn.org/board/topic/135472-faq-what-is-the-uac-part2/

If what it says is true, I guess you only need to manage to add an entry in the task scheduler while installing and it is done!

Is it realistic?

**Comment by alphaonex86** [comment]
Hello,

> I saw in the todo list (
> https://github.com/alphaonex86/Supercopier/blob/master/todo.txt#L6) that
> you have a problem with UAC on Supercopier's startup.
> 
> But after this fix, will call one time the UAC. To prevent, launch in
> administrator.
> 
> This is, for me, the only thing that prevent to test it in a daily basis.
> 
> I know CCleaner https://www.piriform.com/ccleaner uses a method
> involving the Task Scheduler to avoid the UAC prompt to appear.
> I found this article :
> http://www.msfn.org/board/topic/135472-faq-what-is-the-uac-part2/
> 
> If what it says is true, I guess you only need to manage to add an entry
> in the task scheduler while installing and it is done!
> 
> Is it realistic?
> 
> Same as previously say, it's like run as administrator. But it's can be
> degerous for the normal user.
> 
>  —
> Reply to this email directly or view it on GitHubhttps://github.com/alphaonex86/Supercopier/issues/2.

## 

alpha_one_x86 alpha_one_x86@first-world.info
Main developer of Ultracopier, Esourcing and server management
IT, OS, technologies, security and business department

**Comment by dsferruzza** [comment]
Ok!
I guess I should try this method by myself (add a new task + change shortcuts/startup infos) and see ^^
Thanks for your time!
